server:
  port: 9101

spring:
  application:
    name: myshop-user
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: a29180506
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 配置
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

